# Generated by Django 6.0.1 on 2026-07-08 16:20

import django.db.models.deletion
import letters.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(unique=True, verbose_name='අනු අංකය')),
                ('date_received', models.DateField(blank=True, null=True)),
                ('sender_details', models.TextField(blank=True, null=True, verbose_name='Sender Details')),
                ('letter_type', models.CharField(blank=True, max_length=255, null=True)),
                ('accepting_officer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('target_sector', models.CharField(blank=True, choices=[('GOVERNING', 'Governing'), ('HEALTH', 'Health'), ('DEVELOPMENT', 'Development'), ('INCOME', 'Income'), ('ACCOUNTS', 'Accounts')], max_length=20, null=True)),
                ('administrated_by', models.CharField(blank=True, choices=[('-', '-'), ('CHAIRMAN', 'සභාපති'), ('SECRETARY', 'ලේකම්'), ('CMO', 'ප්\u200dරධාන කළමණාකරන නිළධාරී'), ('HOD', 'අංශ ප්\u200dරධානී')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REPLIED', 'Replied'), ('NOT_REQUIRED', 'Not Required'), ('OLD_RECORD', 'Old Record')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('attachment_1', models.FileField(blank=True, null=True, upload_to=letters.models.letter_directory_path)),
                ('attachment_2', models.FileField(blank=True, null=True, upload_to=letters.models.letter_directory_path)),
                ('attachment_3', models.FileField(blank=True, null=True, upload_to=letters.models.letter_directory_path)),
                ('attachment_4', models.FileField(blank=True, null=True, upload_to=letters.models.letter_directory_path)),
                ('attachment_5', models.FileField(blank=True, null=True, upload_to=letters.models.letter_directory_path)),
                ('attachment_6', models.FileField(blank=True, null=True, upload_to=letters.models.letter_directory_path)),
            ],
            options={
                'ordering': ['serial_number'],
            },
        ),
        migrations.CreateModel(
            name='LetterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='letters/pages/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='letters.letter')),
            ],
        ),
        migrations.CreateModel(
            name='SectorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('GOVERNING', 'Governing'), ('HEALTH', 'Health'), ('DEVELOPMENT', 'Development'), ('INCOME', 'Income'), ('ACCOUNTS', 'Accounts')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
