# Generated by Django 6.0.1 on 2026-01-27 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('serial_number', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='අනු අංකය')),
                ('date_received', models.DateField()),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_address', models.TextField(blank=True, null=True)),
                ('letter_type', models.CharField(max_length=255)),
                ('accepting_officer_id', models.CharField(max_length=50)),
                ('target_sector', models.CharField(choices=[('GOVERNING', 'Governing'), ('HEALTH', 'Health'), ('DEVELOPMENT', 'Development'), ('INCOME', 'Income'), ('ACCOUNTS', 'Accounts')], max_length=20)),
                ('administrated_by', models.CharField(choices=[('-', '-'), ('CHAIRMAN', 'සභාපති'), ('SECRETARY', 'ලේකම්'), ('CMO', 'ප්\u200dරධාන කළමණාකරන නිළධාරී'), ('HOD', 'අංශ ප්\u200dරධානී')], max_length=20)),
                ('is_replied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('attachment_1', models.FileField(blank=True, null=True, upload_to='letters/')),
                ('attachment_2', models.FileField(blank=True, null=True, upload_to='letters/')),
                ('attachment_3', models.FileField(blank=True, null=True, upload_to='letters/')),
                ('attachment_4', models.FileField(blank=True, null=True, upload_to='letters/')),
                ('attachment_5', models.FileField(blank=True, null=True, upload_to='letters/')),
                ('attachment_6', models.FileField(blank=True, null=True, upload_to='letters/')),
            ],
        ),
        migrations.CreateModel(
            name='LetterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='letters/pages/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='letters.letter')),
            ],
        ),
        migrations.CreateModel(
            name='SectorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('GOVERNING', 'Governing'), ('HEALTH', 'Health'), ('DEVELOPMENT', 'Development'), ('INCOME', 'Income'), ('ACCOUNTS', 'Accounts')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
