# Generated by Django 6.0.1 on 2026-01-14 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=10, unique=True, verbose_name='අනු අංකය')),
                ('date_received', models.DateField()),
                ('sender_name', models.CharField(max_length=200)),
                ('sender_address', models.TextField()),
                ('letter_type', models.CharField(max_length=200)),
                ('accepting_officer_id', models.CharField(max_length=50)),
                ('target_sector', models.CharField(choices=[('GOVERNING', 'Governing'), ('HEALTH', 'Health'), ('DEVELOPMENT', 'Development'), ('INCOME', 'Income'), ('ACCOUNTS', 'Accounts')], max_length=20)),
                ('administrated_by', models.CharField(choices=[('CHAIRMAN', 'සභාපති'), ('SECRETARY', 'ලේකම්'), ('CMO', 'ප්\u200dරධාන කළමණාකරන නිළධාරී'), ('HOD', 'අංශ ප්\u200dරධානී')], max_length=20)),
                ('is_replied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SectorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('GOVERNING', 'Governing'), ('HEALTH', 'Health'), ('DEVELOPMENT', 'Development'), ('INCOME', 'Income'), ('ACCOUNTS', 'Accounts')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
