# Generated by Django 6.0.1 on 2026-07-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='created_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='updated_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
