# Generated by Django 6.0.1 on 2026-01-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='letters/'),
        ),
        migrations.AddField(
            model_name='letter',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
