# Generated by Django 6.0.1 on 2026-02-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectorprofile',
            name='current_session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
