# Generated by Django 6.0.1 on 2026-01-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='administrated_by',
            field=models.CharField(choices=[('-', '-'), ('CHAIRMAN', 'සභාපති'), ('SECRETARY', 'ලේකම්'), ('CMO', 'ප්\u200dරධාන කළමණාකරන නිළධාරී'), ('HOD', 'අංශ ප්\u200dරධානී')], max_length=20),
        ),
    ]
