# Generated by Django 6.0.1 on 2026-07-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0002_letter_created_by_letter_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='administrated_by',
            field=models.CharField(blank=True, choices=[('CHAIRMAN', 'Chairman'), ('SECRETARY', 'Secretary'), ('CHIEF MANAGEMENT OFFICER', 'Chief Management Officer'), ('HEAD OF SECTION', 'Head Of Section')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REPLIED', 'Replied'), ('NOT_REQUIRED', 'Not Required'), ('OLD_RECORD', 'Old Record')], default='PENDING', max_length=40),
        ),
        migrations.AlterField(
            model_name='letter',
            name='target_sector',
            field=models.CharField(blank=True, choices=[('GOVERNING SECTION', 'Governing Section'), ('HEALTH SECTION', 'Health Section'), ('DEVELOPMENT SECTION', 'Development Section'), ('INCOME SECTION', 'Income Section'), ('ACCOUNTS SECTION', 'Accounts Section')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='sectorprofile',
            name='sector',
            field=models.CharField(choices=[('GOVERNING SECTION', 'Governing Section'), ('HEALTH SECTION', 'Health Section'), ('DEVELOPMENT SECTION', 'Development Section'), ('INCOME SECTION', 'Income Section'), ('ACCOUNTS SECTION', 'Accounts Section')], max_length=20),
        ),
    ]
