# Generated by Django 6.0.1 on 2026-01-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0002_alter_letter_administrated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='letter_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='letter',
            name='sender_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='sender_name',
            field=models.CharField(max_length=255),
        ),
    ]
