# Generated by Django 6.0.1 on 2026-01-23 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0003_alter_letter_letter_type_alter_letter_sender_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='letters/pages/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='letters.letter')),
            ],
        ),
    ]
