# Generated by Django 6.0.1 on 2026-07-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0003_alter_letter_administrated_by_alter_letter_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='target_sector',
            field=models.CharField(blank=True, choices=[('GOVERNING', 'Governing Section'), ('HEALTH', 'Health Section'), ('DEVELOPMENT', 'Development Section'), ('INCOME', 'Income Section'), ('ACCOUNTS', 'Accounts Section')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='sectorprofile',
            name='sector',
            field=models.CharField(choices=[('GOVERNING', 'Governing Section'), ('HEALTH', 'Health Section'), ('DEVELOPMENT', 'Development Section'), ('INCOME', 'Income Section'), ('ACCOUNTS', 'Accounts Section')], max_length=20),
        ),
    ]
