# Generated by Django 6.0.1 on 2026-07-16 19:18

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0004_alter_letter_target_sector_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLetter',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('serial_number', models.IntegerField(db_index=True, verbose_name='අනු අංකය')),
                ('date_received', models.DateField(blank=True, null=True)),
                ('sender_details', models.TextField(blank=True, null=True, verbose_name='Sender Details')),
                ('letter_type', models.CharField(blank=True, max_length=255, null=True)),
                ('accepting_officer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('target_sector', models.CharField(blank=True, choices=[('GOVERNING', 'Governing Section'), ('HEALTH', 'Health Section'), ('DEVELOPMENT', 'Development Section'), ('INCOME', 'Income Section'), ('ACCOUNTS', 'Accounts Section')], max_length=40, null=True)),
                ('administrated_by', models.CharField(blank=True, choices=[('CHAIRMAN', 'Chairman'), ('SECRETARY', 'Secretary'), ('CHIEF MANAGEMENT OFFICER', 'Chief Management Officer'), ('HEAD OF SECTION', 'Head Of Section')], max_length=40, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REPLIED', 'Replied'), ('NOT_REQUIRED', 'Not Required'), ('OLD_RECORD', 'Old Record')], default='PENDING', max_length=40)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('attachment_1', models.TextField(blank=True, max_length=100, null=True)),
                ('attachment_2', models.TextField(blank=True, max_length=100, null=True)),
                ('attachment_3', models.TextField(blank=True, max_length=100, null=True)),
                ('attachment_4', models.TextField(blank=True, max_length=100, null=True)),
                ('attachment_5', models.TextField(blank=True, max_length=100, null=True)),
                ('attachment_6', models.TextField(blank=True, max_length=100, null=True)),
                ('created_by', models.CharField(blank=True, max_length=150, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=150, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical letter',
                'verbose_name_plural': 'historical letters',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
