# Generated by Django 6.0.1 on 2026-07-17 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0005_historicalletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_backup_enabled', models.BooleanField(default=False)),
                ('last_auto_backup_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Backup Settings',
            },
        ),
    ]
